### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by gagayang** [smyhvae/Mac#4]
你好，我遇到一个问题。我的mac是最新版本。但是当我使用node 的npm install 之后应该是会使用npm link这样我就可以使用短命令。但是我执行短命令就会报错。说无法执行二进制文件。请问你遇到过这个问题吗？

**Comment by smyhvae** [comment]
不好意思，不太清楚呢~

**Comment by smyhvae** [comment]
> 你好，我遇到一个问题。我的mac是最新版本。但是当我使用node 的npm install 之后应该是会使用npm link这样我就可以使用短命令。但是我执行短命令就会报错。说无法执行二进制文件。请问你遇到过这个问题吗？

不好意思，不太清楚呢~

**Comment by gagayang** [comment]
哦 没事我也纳闷困扰我好多天了 虽然不影响开发。但是我也很奇怪。

**Comment by smyhvae** [comment]
> 哦 没事我也纳闷困扰我好多天了 虽然不影响开发。但是我也很奇怪。

恩，方便微信学习交流下吗？我微信：bootmei

**Comment by gagayang** [comment]
我的微信 18600574355

**Comment by gagayang** [comment]
公司的加密软件的锅。已经搞定
